# Generated by Django 5.0.1 on 2024-04-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('License_plate', models.CharField(max_length=50)),
                ('Make', models.CharField(max_length=50)),
                ('VIN', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('Date', models.DateField(auto_now=True)),
                ('Miles_Driven', models.CharField(max_length=50)),
            ],
        ),
    ]
