# Generated by Django 5.0.1 on 2024-04-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
