# Generated by Django 5.0.1 on 2024-04-09 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_data_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Date',
            new_name='date_str',
        ),
    ]
