# Generated by Django 5.0.1 on 2024-04-09 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_date_data_date_str'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Vehicle_Data',
        ),
    ]
