# Generated by Django 5.0.1 on 2024-04-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_data_vehicle_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle_Data',
            new_name='VehicleData',
        ),
    ]
