# Generated by Django 5.0.1 on 2024-04-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_vehicle_data_vehicledata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicledata',
            old_name='License_plate',
            new_name='LicensePlate',
        ),
        migrations.RenameField(
            model_name='vehicledata',
            old_name='Miles_Driven',
            new_name='MilesDriven',
        ),
    ]
